app:
    resource: '@AppBundle/Controller/DefaultController.php'
    type: annotation

arenas:
    type:     rest
    resource: AppBundle\Controller\ArenaController

sportCourts:
    type:     rest
    resource: AppBundle\Controller\Arena\SportCourtController

users:
    type:     rest
    resource: AppBundle\Controller\UserController