AppBundle\Entity\User:
    exclusion_policy: none
    properties:
        id:
            groups: ['user','userall', 'auth-token']
        firstname:
            groups: ['user','userall', 'auth-token']
        lastname:
            groups: ['user','userall', 'auth-token']
        email:
            groups: ['user','userall', 'auth-token']
